services:
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    ports:
      - ${BACKEND_PORT}:4000
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BACKEND_CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_CONTAINER_POST=${BACKEND_CONTAINER_POST}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定

  db:
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: postgres:17.2
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d #初期データ
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}"
